FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y openssh-server && \
    mkdir /var/run/sshd && \
    echo 'root:CHANGEME' | chpasswd && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    # SSH login fix. Otherwise user is kicked off after login
    sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"

RUN echo "export VISIBLE=now" >> /etc/profile && \
    useradd -m -d /home/ansible-usr ansible-usr && \
    mkdir /home/ansible-usr/.ssh

COPY .ssh/id_rsa.pub /home/ansible-usr/.ssh/authorized_keys

RUN chown -R ansible-usr:ansible-usr /home/ansible-usr/.ssh && \
    chmod 700 /home/ansible-usr/.ssh && \
    chmod 640 /home/ansible-usr/.ssh/authorized_keys

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
